### ISSUE TITLE
Recover for panics in function Handler for HTTP mode

### ISSUE THREAD

**Issue by s8sg** [openfaas/golang-http-template#27]
In current code we are calling the http function handler as
```go
result, resultErr := function.Handle(req)
```
In case there is a panic inside the handler the `handler` server process will exit, failing the future requests for the same. 

Optionally it can be handled with a `recover` as:
```go
defer func() {
       if recoverLog := recover(); recoverLog != nil {
               log.Print(recoverLog)
               w.WriteHeader(http.StatusInternalServerError)
       }
}()
result, resultErr := function.Handle(req)
```
In this case the `handler` server keep running

**Comment by LucasRoesler** [comment]
I like this, is it something you would be willing to also contribute?

**Comment by s8sg** [comment]
@LucasRoesler Sure

**Comment by alexellis** [comment]
Hi, thanks for your suggestion.

This is actually by design. I think that it should fail and that the container should be restarted.

If someone has a specific need for a catch-all, then the PR can be forked. I might change my mind in the future, but this is where I am on it at the moment. 

Alex

**Comment by s8sg** [comment]
That make sense. One can handle the panic inside the request handler itself and return a response accordingly. It gives more flexibilities to determine whether to recover or not

**Comment by alexellis** [comment]
I appreciate the suggestion. Please keep on helping us to make OpenFaaS better 👍
