### ISSUE TITLE
Improve caching for sub-package cache

### ISSUE THREAD

**Issue by Place1** [openfaas/golang-http-template#42]
I'm currently using `golang-middleware` and following the Advanced use-case where you have your own go package in a subfolder and make use of `GO_REPLACE.txt`.

The template works for me so far but build/deploy is very slow because it downloads dependencies every time.

Is there a way we could improve the Dockerfile so that a `go mod download` could be cached?

**Comment by alexellis** [comment]
Why do you think the modules are downloaded each time? Do you want to provide a sample that reproduces this?

(next time, if you use the template, you will see that we ask for all of these things on issues)
