### ISSUE TITLE
Add multi-arch support, with fallback to current behaviour

### ISSUE THREAD

**Issue by alexellis** [openfaas/golang-http-template#47]
## Task

Add multi-arch support, with fallback to current behaviour

Update the existing Dockerfiles as per: https://github.com/alexellis/multiarch-templates/blob/master/template/go-multiarch/Dockerfile

## Testing instructions

Test as per: https://github.com/alexellis/multiarch-templates

And make sure that `faas-cli up` still works without any multi-arch considerations.

**Comment by utsavanand2** [comment]
I would love to take a go at this

**Comment by alexellis** [comment]
Please do. You should just need to copy and paste from the example above.

**Comment by utsavanand2** [comment]
@alexellis PR #48 addresses this issue
