### ISSUE TITLE
Enable Go modules as a default

### ISSUE THREAD

**Issue by alexellis** [openfaas/golang-http-template#62]
## Description

Enable Go modules as a default

Update the templates to use GO111MODULE=on as a default

Then clarify in the docs or the README here how to turn it off, for those who need to vendor private code.

## Testing

Test end to end to show that the build arg to turn off modules still works

Show output that also shows the default is working without additional settings.

**Comment by alexellis** [comment]
/add label: good first issue, help wanted

**Comment by cpanato** [comment]
i will work on that, expected to have a pr by the end of the week

**Comment by alexellis** [comment]
Thanks Carlos
