### ISSUE TITLE
golang-middleware: Body not closed

### ISSUE THREAD

**Issue by alexellis** [openfaas/golang-http-template#8]
In the default handler for golang-middleware the body is not closed of the request. This is generally done when reading the body.

I'd expect to see something like: 

```golang
defer r.Body.Close()
```

**Comment by alexellis** [comment]
cc @stefanprodan

**Comment by alexellis** [comment]
https://github.com/openfaas-incubator/golang-http-template/blob/master/template/golang-middleware-armhf/main.go#L16

https://github.com/openfaas-incubator/golang-http-template/blob/master/template/golang-middleware/main.go#L16

**Comment by 0sc** [comment]
Can I work on this?

**Comment by alexellis** [comment]
Sure, are you confident you can do the testing too?

Alex

**Comment by 0sc** [comment]
I can try. What should the testing look like?

**Comment by alexellis** [comment]
Building a function with the template, deploying it and invoking it.

**Comment by 0sc** [comment]
I was thinking since the issue is about fixing the not closed request body, testing with default http requests might suffice.

**Comment by alexellis** [comment]
Derek close: fixed by @rdimitrov

**Comment by alexellis** [comment]
@0sc there's a couple of more small issues on this repo if you're interested.
