### ISSUE TITLE
Timeout should match value in read/write_timeout

### ISSUE THREAD

**Issue by alexellis** [openfaas/golang-http-template#9]
## Expected

Timeout value in main.go should match value in read/write_timeout env-vars (these are Golang durations)

## Actual

Hard-coded to 3 seconds

This is the same in both variants of the template.

## Merge criteria

For a merge this will need:

* demonstrated (with console output) end-to-end testing showing timeout met and cancelled, a request within timeout limits
* golang-http and golang-middleware both need to be updated including armhf versions

**Comment by alexellis** [comment]
@ewilde PTAL?

**Comment by ewilde** [comment]
Closed by #23

**Comment by ewilde** [comment]
Derek close
